---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: ${REPO_BRANCH}
    service: ${REPO}
  triggers:
  - type: commit
  properties:
  - name: REPO_BRANCH
    value: ${REPO_BRANCH}
  jobs:
  - name: Build
    type: builder
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: REPO_BRANCH
    value: ${REPO_BRANCH}
  - name: SPACE
    value: ${SPACE_NAME}
    type: text
  - name: APIC_URL_US
    value: ${APIC_URL_US}
    type: text
  - name: CF_APP_NAME
    value: ${CF_APP_NAME}
    type: text
  - name: REGION
    value: ${REGION_ID}
  - name: ORG
    value: ${ORG_NAME}
  - name: BLUEMIX_API_KEY
    value: ${BLUEMIX_API_KEY}
  - name: SPACE
    value: ${SPACE_NAME}
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      ./.bluemix/pipeline-DEPLOY.sh