---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: ${REPO_BRANCH}
    service: ${REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build image
    type: builder
    build_type: cr
    artifact_dir:
    target:
      region_id: ${REGION_ID}
      api_key: ${BLUEMIX_API_KEY}
    namespace: ${REGISTRY_NAMESPACE}
    image_name: MULTIPLE_IMAGES
    script: |
      #!/bin/bash
      ./.bluemix/pipeline-BUILD.sh
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build image
  jobs:
  - name: Deploy Kubernetes Pod
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      api_key: ${BLUEMIX_API_KEY}
      kubernetes_cluster: ${KUB_CLUSTER_NAME}
    script: |
      #!/bin/bash
      ./.bluemix/pipeline-DEPLOY.sh